### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by luthfirangers** [ognev-zair/Kotlin-AgendaCalendarView#7]
Hi @ognev-zair , I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by ognev-zair** [comment]
Hi @luthfirangers!
Yeah, that would be awesome!

**Comment by luthfirangers** [comment]
![calendar](https://user-images.githubusercontent.com/39691169/42838912-3b447574-8a2c-11e8-94c9-d37091b120fa.png)

I have designed it, how do you think? do you like it

**Comment by ognev-zair** [comment]
Feel free to contribute
